export const supriseMePrompts =[ 
"Create a post showcasing our latest product and its unique features.",
"Generate a motivational quote aligned with our brand values.",
"Craft a captivating caption for an upcoming product launch.",
"Generate a teaser image for our next big announcement.",
"Write a post highlighting a customer success story.",
"Create a social media poll related to our industry trends.",
"Generate a fun fact related to our business niche.",
"Craft a caption that encourages audience interaction.",
"Write a post about the benefits of our service.",
"Generate an attention-grabbing headline for a blog post.",
"Create an infographic showcasing industry statistics.",
"Craft a caption that showcases our company culture.",
"Write a post addressing a common customer question.",
"Generate an image showcasing a behind-the-scenes moment.",
"Craft a caption for an upcoming event or webinar.",
"Create a post highlighting our commitment to sustainability.",
"Generate a visual post comparing our product versions.",
"Write a post discussing the latest industry news.",
"Craft a caption for a giveaway or contest announcement.",
"Generate a tip related to using our product effectively.",
"Create an image post featuring a customer testimonial.",
"Craft a caption that promotes our limited-time offer.",
"Write a post sharing a recent achievement or milestone.",
"Generate a meme that resonates with our target audience.",
"Craft a caption for a 'Did You Know?' series.",
"Create a post about the process of creating our product.",
"Generate a list of resources related to our industry.",
"Craft a caption that invites followers to share their thoughts.",
"Write a post showcasing our company's core values.",
"Generate a creative content teaser for an upcoming project.",
"Craft a caption for a user-generated content spotlight.",
"Create a post discussing the importance of customer feedback.",
"Generate an image that visualizes a common problem we solve.",
"Craft a caption for a post highlighting our team members.",
"Write a post addressing a popular industry misconception.",
"Generate a visual post comparing our service tiers.",
"Craft a caption for a 'Tip of the Day' series.",
"Create a post sharing an interesting industry statistic.",
"Generate a quote from our CEO about our company's vision.",
"Craft a caption for a product maintenance or care tip.",
"Write a post spotlighting our community engagement efforts.",
"Generate an image post featuring a product demo.",
"Craft a caption for a sneak peek of an upcoming project.",
"Create a post discussing the future of our industry.",
"Generate a visual post illustrating a customer journey.",
"Craft a caption for a post addressing a current trend.",
"Write a post about the story behind our brand logo.",
"Generate a humorous post related to our business.",
"Craft a caption for a post celebrating a company anniversary.",
"Create a post sharing a success tip for entrepreneurs.",
]